sudo: required

services:
  - docker

before_install: 
  - docker build -t dockerdev file -f Dockerfile.dev .

script: 
  - docker run -e CI=true dockerdev npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-south-1"
  app: "docker-myreactapp"
  env: "Dockermyreactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-989497181371"
  bucket_path: "docker-myreactapp"
  on:
    branch: master